### ISSUE TITLE
Feedburner - retrieve_csvs krasjer pga feeds med mindre statistikk-data

### ISSUE THREAD

**Issue by tobinus** [RadioRevolt/statistics#2]
Feedburner-feeds har per default ikke "link views" og "link clickthroughs", og dette må aktiveres ved å gå inn på den aktuelle feeden (innlogget som it@radiorevolt.no), klikke «Configure Stats» og huke av for «Item views» og «Item link clicks». 

Problemet er at podcast.management.commands.retrieve_csvs.py antar at disse innstillingene gjelder for samtlige feeds, hvilket ikke nødvendigvis stemmer. For eksempel Skammekroken og UKEsenderen har ikke hatt disse innstillingene aktivert, hvilket har resultert i at podkaststatistikken ikke har kunnet oppdatere seg.
### Work-around

sørge for at disse innstillingene gjelder for **samtlige** podkaster, og sikre at de som legger til feeds i Feedburner vet om dette (kunnskapsoverføring!!).
### Fix

Legg til sjekk der den første raden (med navn på kolonnene) analyseres, og dropp data for kolonner som ikke er representert i CSV-filen. Advar noen om at noe av dataene mangler.
### Tanker

Sånn jeg ser det er det _mulig_ å basere oss på work-arounden alene, men jeg er redd systemet vil knele i framtida når nye radioteknikere ikke har fått overført denne kunnskapen. Det spørs hvor lenge feedburner holde oppe da, hvis vi først skal tenke langsiktig…

**Comment by trygvebw** [comment]
De andre dataene enn "item link clicks" er så å si ubrukelige, og derfor tok jeg ikke hensyn til dette da jeg skrev koden. At retrieve_csvs krasjer når "item link clicks" ikke finnes er for min del helt OK, siden disse uansett MÅ være aktivert for at statistikksiden skal ha noen verdi.

**Comment by tobinus** [comment]
Skjønner. Foreslår vi legger til logikk slik at «nettlesertingen» huker av disse innstillingene på Feedburner-sida hvis CSV-fila har for få kolonner, og laster ned CSV-fila på nytt etter å ha lagret endringene. Hvis det er for mye, synes jeg vi må være å sørge for god kunnskapsoverføring, slik at de som legger til podkaster i Feedburner er klar over dette.

**Comment by tobinus** [comment]
> Foreslår vi legger til logikk slik at «nettlesertingen» huker av disse innstillingene på Feedburner-sida hvis CSV-fila har for få kolonner, og laster ned CSV-fila på nytt etter å ha lagret endringene.

Implementert i c17c7a57529.
